-- Add these lines to ~/.config/hypr/bindings.lua.
o.bind("CTRL + ALT + SHIFT + F1", "Touch Bar: Omarchy menu", "omarchy-menu toggle")
o.bind("CTRL + ALT + SHIFT + F2", "Touch Bar: Terminal", "uwsm-app -- xdg-terminal-exec")
o.bind("CTRL + ALT + SHIFT + F3", "Touch Bar: Toggle dictation", "voxtype record toggle")
o.bind("CTRL + ALT + SHIFT + F4", "Touch Bar: Screenshot", "omarchy-capture-screenshot")
o.bind("CTRL + ALT + SHIFT + F5", "Touch Bar: Display brightness down", "~/.local/bin/touchbar-brightness display down", { locked = true, repeating = true })
o.bind("CTRL + ALT + SHIFT + F6", "Touch Bar: Display brightness up", "~/.local/bin/touchbar-brightness display up", { locked = true, repeating = true })
o.bind("CTRL + ALT + SHIFT + F7", "Touch Bar: Keyboard brightness down", "~/.local/bin/touchbar-brightness keyboard down", { locked = true, repeating = true })
o.bind("CTRL + ALT + SHIFT + F8", "Touch Bar: Keyboard brightness up", "~/.local/bin/touchbar-brightness keyboard up", { locked = true, repeating = true })

o.bind("SUPER + CTRL + SHIFT + F1", "Touch Bar app: Zen", "uwsm-app -- zen-browser")
o.bind("SUPER + CTRL + SHIFT + F2", "Touch Bar app: Herdr", "uwsm-app -- xdg-terminal-exec -- herdr")
o.bind("SUPER + CTRL + SHIFT + F3", "Touch Bar app: TradeWasm", "uwsm-app -- tradewasm")
o.bind("SUPER + CTRL + SHIFT + F4", "Touch Bar app: YouTube Music", "omarchy-launch-or-focus-webapp 'YouTube Music' 'https://music.youtube.com/'")
o.bind("SUPER + CTRL + SHIFT + F5", "Touch Bar app: YouTube", "omarchy-launch-webapp 'https://youtube.com/'")
o.bind("SUPER + CTRL + SHIFT + F6", "Touch Bar app: X.com", "omarchy-launch-webapp 'https://x.com/'")
o.bind("SUPER + CTRL + SHIFT + F7", "Touch Bar app: Claude", "uwsm-app -- xdg-terminal-exec -- claude")
o.bind("SUPER + CTRL + SHIFT + F8", "Touch Bar app: Codex", "uwsm-app -- xdg-terminal-exec -- codex")
o.bind("SUPER + CTRL + SHIFT + F9", "Touch Bar app: Gemini", "uwsm-app -- xdg-terminal-exec -- gemini")
o.bind("SUPER + CTRL + SHIFT + F10", "Touch Bar app: Gmail", "omarchy-launch-webapp 'https://mail.google.com/'")
o.bind("SUPER + CTRL + SHIFT + F11", "Touch Bar app: Files", "uwsm-app -- nautilus --new-window")
